options {
    directory "/var/cache/bind";
    listen-on { 172.30.0.23; };
    listen-on-v6 { none; };
    recursion no;
    allow-query { any; };
};
zone "zeta.unsigned" {
    type primary;
    file "/var/lib/bind/db.zeta.unsigned";
};
