options {
    directory "/var/cache/bind";
    listen-on { 172.30.0.80; };
    listen-on-v6 { none; };
    recursion no;
    allow-query { any; };
};
zone "delta.signed" {
    type primary;
    file "/var/lib/bind/db.delta.signed";
};
