options {
    directory "/var/cache/bind";
    listen-on { 172.30.0.73; };
    listen-on-v6 { none; };
    recursion no;
    allow-query { any; };
};
zone "badalg.test" {
    type primary;
    file "/var/lib/bind/db.badalg.signed";
};
