options {
    directory "/var/cache/bind";
    listen-on { 172.30.0.72; };
    listen-on-v6 { none; };
    recursion no;
    allow-query { any; };
};
zone "nods.test" {
    type primary;
    file "/var/lib/bind/db.nods.signed";
};
