options {
    directory "/var/cache/bind";
    listen-on { 172.30.0.22; };
    listen-on-v6 { none; };
    recursion no;
    allow-query { any; };
};
zone "epsilon.unsigned" {
    type primary;
    file "/var/lib/bind/db.epsilon.unsigned";
};
