options {
    directory "/var/cache/bind";
    listen-on { 172.30.0.71; };
    listen-on-v6 { none; };
    recursion no;
    allow-query { any; };
};
zone "expired.test" {
    type primary;
    file "/var/lib/bind/db.expired.signed";
};
