options {
    directory "/var/cache/bind";
    listen-on { 172.30.0.21; };
    listen-on-v6 { none; };
    recursion no;
    allow-query { any; };
};
zone "alpha.unsigned" {
    type primary;
    file "/var/lib/bind/db.alpha.unsigned";
};
