options {
    directory "/var/cache/bind";
    listen-on { 172.30.0.150; };
    listen-on-v6 { none; };
    recursion yes;
    allow-recursion { 172.30.0.0/24; };
    allow-query { any; };
    dnssec-validation yes;
};
trust-anchors {
    "." initial-key 257 3 13 "y2BXLq+mZmOfQ6OTxFvYXZh918GVn4IKRk6IiCFvK40GcX+jrXhGu82j 4xThc0nrdsrueAvn2b/djrBR4grZDg==";
};
zone "." {
    type hint;
    file "/var/lib/bind/db.root.hints";
};
